### ISSUE TITLE
how to get payload on rtm.start ?

### ISSUE THREAD

**Issue by marktheis** [slackhq/node-slack-client#145]
How do you get the whole payload on rtm.start?
I've looked a bit through the source, but can't really figure it out.

An example would be great :)
version 2.0.2

**Comment by pekim** [comment]
When the RTM_CONNECTION_OPENED event has fired, your datastore will be populated with the received data.

Although it doesn't appear to be available immediately, but is in the next event loop tick (hence the `setImmediate` in my snippet below). I suspect that this is because the event is triggered right before the datastore is populated, but I haven't looked at that bit of code.

Perhaps there's a better, slightly later, event to wait for? I think that I need to look in to the source a bit more.

```javascript
  const dataStore = new MemoryDataStore({
    logger: log
  });

  const rtm = new RtmClient(getPreferenceToken(), {
    dataStore,
    logger: log
  });

  rtm.on(CLIENT_EVENTS.RTM.RTM_CONNECTION_OPENED, () => {
    setImmediate(() => {
      console.log(dataStore.channels);
    });
  });

  rtm.start();
```

**Comment by marktheis** [comment]
Thank you. Just what I needed. I'll let the the issue remain open until someone from slack can confirm whether or not there is any other way to do it.

**Comment by l12s** [comment]
Hey there, I've updated the RTM client to also emit the rtm.start payload. You can see an example of how to capture that in the README: https://github.com/slackhq/node-slack-client/blob/master/README.md#capturing-the-rtmstart-payload
