### ISSUE TITLE
how to use webClient?

### ISSUE THREAD

**Issue by benzmuircroft** [slackhq/node-slack-client#148]
You have **no** docs for the node webClient part at all except one tiny example

1. I would like to create a channel called guest-user123
2. post to that channel as guest-user123
3. listen to messages on that channel

and how do i get the channel id **there are no node.js examples of any of this stuff**

    rtm.sendMessage('this is a test message', 'C0CHZA86Q', function messageSent(){

the main docs are flim-flam only theory and waffle and are just sort of like an attempt to describe red and green to a blind guy... example please

**Comment by benzmuircroft** [comment]
tiny mention

https://github.com/slackhq/node-slack-client/blob/master/examples/example-web-client.js

**Comment by Everesty** [comment]
First and foremost, there technically are docs (see #144). All of the source for the project is documented via [jsdoc](http://usejsdoc.org/). The jsdocs aren't exported, though. That means if you want documentation for something specific to this node module, all you have to do is a little looking around in the code that this repository provides.

However, there are another set of docs: https://api.slack.com/. More specifically, you're looking for https://api.slack.com/methods. Any method listed there *should be a function of a web client object.* As for the arguments you need to pass to each function, you'll have to reference the [corresponding faucet file](https://github.com/slackhq/node-slack-client/tree/master/lib/clients/web/facets), though most are fairly straightforward.

I hate doing this, but for your sake I believe an example would be the best way to explain how to use the web client. **Do note that none of this is tested. I simply wrote it up in an effort to explain how you should go about trying to use the module and api.** Furthermore, it's been some time since I've used this module. There may be better ways of doing what you want than what I'm say.

---

### Creating a channel

So, assuming you already have your web client created (let's call it `webClient`), we want to create a channel. Looking at http://api.slack.com/methods, it's obvious that we want to use the [`channels.create`](https://api.slack.com/methods/channels.create) method. So, let's do that:

```js
// Create a channel named "guest-user123"
webClient.channels.create('guest-user123', function(err, channelResponse) {
    // TODO check for errors
    // Channel was created!
});
```

For the sake of example, I did skip checking `err` and checking `channelResponse.ok`; if `ok` is false then there'll be a corresponding `error` field to the response object. Nevertheless, just know that **you should always check for errors** and handle them if they're thrown.

#### Posting to the channel

So, we created the channel. Checking back to the Response section of [`channels.create`](https://api.slack.com/methods/channels.create) we see that it gives us a plethora of information, ranging from the channel id, to the name, it's creator id, and various other data.

We want to post to the channel, so we'll need to use [`chat.postMessage`](https://api.slack.com/methods/chat.postMessage). We'll need the channel id (`channelResponse.channel.id`) and some text to post. If we want to post as the user "guest-user123" then we'll need to provide `username: "guest-user123"` as an option.

Picking up where we left off last time:

```js
// Channel was created!
webClient.chat.postMessage(
    response.channel.id,
    'The Law of Dominance of Knives is quite interesting to think about',
    { username: 'guest-user123' },
    function(err, messageResponse) {
        // TODO check for errors
    }
);
```

As for listening for messages on the new channel, I believe the RTM client should do that automatically.

---

The lack of knowledge about how to use this node module, however, does seem to be something I'd consider an issue (good thing there's already one for that: #144). Maybe using the GitHub wiki? http://readthedocs.org? In any case, I think some docs (or more/better examples) specific to this project would be a good idea.

**Comment by l12s** [comment]
That's an amazing write-up - thanks so much @Everesty 

I've added a more specific issue to track documentation - https://github.com/slackhq/node-slack-client/issues/149 - which tracks getting useful JSDoc docs generated from the code. The existing output isn't especially helpful and is less useful than just reading the code itself.

**Comment by benzmuircroft** [comment]
yeah thanks dude!!
