### ISSUE TITLE
2.2.1 How to open a DM for the first time

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#184]
In the previous version, I used to open it using client.openDM(slack_id, callback). Now the method does not exist anymore. How can I open a DM for the first time?

**Comment by Everesty** [comment]
I feel like I've [written something like this before](https://github.com/slackhq/node-slack-client/issues/148#issuecomment-190013843), but I'll do it again. Do be warned, however, that I've been awake for less than an hour and this whole post may be but a jumble of words to you. Basically, check the aforementioned write-up if any of the below is confusing.

First and foremost, the [Slack API docs](https://api.slack.com/) is (are?) your best friend when using this module. Specifically, the [methods](https://api.slack.com/methods) and [events](https://api.slack.com/events) sections, as they tell you what the names of events and methods are, plus they also detail what data is sent back/requried.

Second, you should make sure you understand the difference between the RTM client and the web client; the RTM client is used for accepting events, the web client is used for sending methods.

Looking at the method listing, it's quite obvious we want the [`im.open`](https://api.slack.com/methods/im.open) method. So, since it's a method, we'll use the web client.

    webClient.im.open(someUserId, function(err, resp) {
        // Check `err` for any errors.
        // `resp` is the parsed response from the api.
        // Check API docs for what `resp` can be.
    });

:balloon: :tada: :balloon:

---

I did lie a little earlier in implying that you can't use the RTM client for sending methods, you actually can. Both clients (the RTM client and web client) inherit from a `BaseAPIClient` class, which has a `makeAPICall` method. Using that method, you can make a method call, so long as you provide an endpoint and optionally parameters and/or a callback.

What the RTM client doesn't do is create the facet instances as children of itself. Basically put, you can't access methods via the RTM client like you can with the web client by calling the endpoint as a child of the client.

Side note: The `im` facet is special in that you can either call it `im` or `dm` when using the module. Nothing about this info is really needed to be able to do something, just a nice tidbit of knowledge.

**Comment by brunosiqueira** [comment]
Thanks, @Everesty 
I am using the rtm client and makeAPICall did the trick!

**Comment by l12s** [comment]
Thanks @Everesty!
