### ISSUE TITLE
DM In Channel

### ISSUE THREAD

**Issue by casche** [slackhq/node-slack-client#38]
Is there anyway for a bot to be able to send a DM directly in the channel ? So that other users cannot see it?

**Comment by jtatum** [comment]
There is not. Sometimes you appear to see slackbot doing something like that, but it is a client-side response to errors and other events received, not slackbot actually sending you a message that only you can see.

**Comment by dfarr** [comment]
This would be a cool feature to have! Personalized responses to other messages in the right context.

**Comment by danbovey** [comment]
+1

**Comment by trevinwoodstock** [comment]
+1, I'd like this too.

**Comment by l12s** [comment]
You can do this with Slash commands in some cases, check out the "In Channel" vs "Ephemeral" responses section of https://api.slack.com/slash-commands

If that's not what you're looking for, I'd suggest reaching out via our support channels as it's a core API feature request rather than the node client.

**Comment by scottmont** [comment]
I have been trying to implement this in many ways even hijacking errors codes to no avail.  Would be great if this worked.  response_type: ephemeral does nothing :(
