### ISSUE TITLE
Handle team_migration_started events

### ISSUE THREAD

**Issue by andebor** [slackhq/node-slack-client#51]
The client seems to be missing handling for [team_migration_started](https://api.slack.com/events/team_migration_started) events.

```
[Tue May 26 2015 18:24:22 GMT+0000 (UTC)] DEBUG Unknown message type: team_migration_started
[Tue May 26 2015 18:24:22 GMT+0000 (UTC)] DEBUG { type: 'team_migration_started' }
```

When this event occurs the client gets disconnected and doesn't get back online. As stated in the docs, a reconnect should be initated when this message is received. This might be related to #5.

**Comment by mrsmn** [comment]
:+1:

**Comment by voneiden** [comment]
Also seeing this happening.. on average perhaps once a month.

**Comment by vanm** [comment]
@grantmd @paulhammond @evansolomon Any chance you guys can review this?  I've been logging this event and am seeing it regularly and slack-client isn't reconnecting w/o this change.

**Comment by ngtjah** [comment]
Seeing this problem almost daily..

```
[Thu Nov 05 2015 20:41:02 GMT-0700 (MST)] DEBUG pong
[Thu Nov 05 2015 20:41:07 GMT-0700 (MST)] DEBUG ping
[Thu Nov 05 2015 20:41:08 GMT-0700 (MST)] DEBUG pong
[Thu Nov 05 2015 20:41:12 GMT-0700 (MST)] DEBUG ping
[Thu Nov 05 2015 20:41:12 GMT-0700 (MST)] DEBUG pong
[Thu Nov 05 2015 20:41:14 GMT-0700 (MST)] DEBUG Unknown message type: team_migration_started
[Thu Nov 05 2015 20:41:14 GMT-0700 (MST)] DEBUG { type: 'team_migration_started' }
```

pong ping stops and then I have 1-way communication

**Comment by l12s** [comment]
Hey,

I'm going to give a proper update on this soon, but we're working on doing some significant client refactoring that'll address this issue and more. I'll be putting together a full update and change log in the next week or so that'll talk to what that will look like.

I appreciate your patience while we work on this!

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve these issues.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

It also includes substantially improved reconnection logic and handling, for both routine disconnects as well `team_migration_started` events and similar. I'll also be making sure to expedite fixes for any issues with reconnection logic in particular, as I know that's been a pain for folks in the past.

So, I'd suggest that the best way to resolve this issue is to upgrade to the latest version. If you have any problems in doing that, please create a new issue and I'll try and help you in there.
