### ISSUE TITLE
Get User Id from Username

### ISSUE THREAD

**Issue by udayms** [slackhq/node-slack-client#73]
Is there a simple way to get the UserId by supplying the Username?

**Comment by meteormanaged** [comment]
https://api.slack.com/rtm

it's all in the API docs for the RTM.

**Comment by CaptainPalapa** [comment]
I added these functions to the 'slack' object in my primary script.  If a
value you pass to either function is what its supposed to return then it
just returns the same value.



Slack.prototype.convertToUserID = function(key){
// Send either a U123456 UserID or bob UserName and it will return the
U123456 value all the time
if(key in this.users) { return key; } // This string must already be a user
ID
for( var userid in this.users ){
if( this.users[userid].name == key ){ return userid; }
}
}
Slack.prototype.convertToUserName = function(key){
// Send either a U123456 UserID or bob UserName and it will return the bob
value all the time
for( var userid in this.users ){
if( userid == key || this.users[userid].name == key ){ return
this.users[userid].name ; }
}
}

**Comment by udayms** [comment]
Thanks CaptainPalapa :+1: This is exactly what I was looking for! :) Let me check this out.

**Comment by bradennapier** [comment]
This is counter-intuitive because if you use a tag `@bradynapier` it doesnt translate that to a user id automatically so there would be no way then to know the actually user being mentioned?

**Comment by aoberoi** [comment]
@bradennapier this was a little unclear, but let me try to clarify.

Slack has deprecated usernames [in favor of display names](https://api.slack.com/changelog/2017-09-the-one-about-usernames). If you're receiving messages over the RTM API, you'll have to parse the mention syntax (explained in the previous link) to extract a user ID. You should never use a username to programmatically refer to a user or bot, only this ID. Mentioning that use in a message is just a matter of formatting your message using the mention syntax. If you'd like to display the user name (like on a web page) then you can use the `users.info` Web API method to find that user's display name.

**Comment by pOoOf** [comment]
Iterating over thousands of users to get one of the user's id from his username is too resource intensive. Is there is any other way of getting users id form email or username ??

**Comment by aoberoi** [comment]
@pOoOf glad you asked. there's the [`users.lookupByEmail` Web API method](https://api.slack.com/methods/users.lookupByEmail) that can be used to find a user by the email address.

Since we're discouraging the use of `username`, I don't think its likely that we'd create a similar new lookup Web API method to do the same for usernames.

Just so I understand your use case, is the problem that you've now persisted a bunch of `username` values in some database or storage, and now each time your app needs to use the ID, you'll have to make this expensive call/iteration to translate that to a user ID? If so, I have some recommendations:

1. Would it be feasible to do a migration on your database so that this expensive operation doesn't happen in the runtime of you application, but rather happens in a one-off migration script that writes the user ID back to the record that contained the username earlier. Then you can deploy an update to your app code that starts depending on the user ID directly.

2. If the above isn't possible, maybe you can change your schema to add a user ID field with a default value (like `NULL`), and then change your application code to look at the user ID for its use, but when it finds the default value, it does this expensive operation for just that first time, and writes the resulting user ID it finds back to the database. That way the expensive operation only takes place once per user.

If the use case is not related to persisted data, then I believe Slack's APIs all provide the user ID alongside anywhere the user name would have been before, so you shouldn't need to make that expensive call/iteration. If you find a place where that's not true, I'd love to hear about it so we can help make that easier.

**Comment by pOoOf** [comment]
Thanks a lot, I have been looking for this.

**Comment by makoConstruct** [comment]
@CaptainPalapa, where is `this.users` documented?

**Comment by aoberoi** [comment]
@makoConstruct `this.users` no longer exists. That comment was written when v2.x of the package was the latest version, and today v5.x is the latest. Specifically, the `Slack` object no longer exists, and that functionality is now split into two different objects (`WebClient` and `RTMClient`) in two different packages (`@slack/web-api` and `@slack/rtm-api`). 

Today, we still recommend using `users.list` and looping over the results to find the user ID from a username. However, before you go down this road, I strongly encourage you to reconsider why you might be using a username in the first place. In almost all cases, Slack will refer to the user by its ID in the first place, so using a username at all is discouraged. 

If you have any details of the problem you’re trying to solve that you can share, I’d be happy to help recommend a more specific solution.

**Comment by makoConstruct** [comment]
The thing I wanted to do was allow people to arrange information with the bot, in reference to other users, but without having to use peoples @s and notify them every time they're mentioned.

I'm aware that non-@ed usernames would be ambiguous, because users can have the same name at the same time, but in those cases (they'd be rare) it would detect it and return an error (and recommend using a @ as a workaround).

I guess I can just mandate using @s, it's not too bad. I'm disappointed though. I kind of want an api for querying the userlist.

**Comment by aoberoi** [comment]
Got it, that makes sense!

I’m sorry that we don’t have an API to search usernames or display names specifically at this time. I’ll take the feedback to the team to see what we can offer in the future.

If you still want to support the mentions without the @ symbol, I can still think of a way to do it. You can use `users.list` to fetch a list of all the users and you can “search” for the right user by iterating over that list. The `WebClient.paginate()` method should help make this really simple to do in a `for await` loop.

If performance or rate limiting becomes an issue (since you’d be making potentially multiple requests to perform this search) then you can consider caching the user list for some amount of time (e.g. 5 minutes) and only re-fetch the list when the previous list is older than that amount of time. The old functionality you asked about was basically implemented in a similar way (a cached users list).

**Comment by kkomelin** [comment]
The easiest way to get User ID by `@username` mentioned in command text is to [enable escaping usernames](https://stackoverflow.com/a/51469610/1762849) through your command settings.
