### ISSUE TITLE
channel.send silently fails after a while

### ISSUE THREAD

**Issue by evil-shrike** [slackhq/node-slack-client#86]
I have a bot running for days. It sometimes sends something or responses to special commands. I noticed that after some time being run the bot's messages aren't appeared in channels. I can see that the bot sent a message (I have logging) but there are nothing happened in Slack.  
At some time my bot sends two messages in a row, the first one via `channel.send` and the second one via `channel.postMessage` (I do this for unfurl_links). Only the second message (sent via `postMessage`) appeared in the channel. If I restart the bot everything starts working fine again.

**Comment by ekmartin** [comment]
The reason `postMessage` completes is that it uses the [Web API](https://api.slack.com/methods/chat.postMessage), while `send` uses websockets. The latter requires the bot to be connected to Slack's realtime API, while the former, `postMessage`, does not.

There's a few issues that could cause the bot to lose connection, such as #54. If you set the environment variable `SLACK_LOG_LEVEL` to debug you'll see a few additional events in stdout, such as `team_migration_started`.

**Comment by evil-shrike** [comment]
Ok, thanks, I've enabled logging and leave the bot running. We'll see in a day or two.

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve this issue.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

It also includes substantially improved reconnection logic and handling, for both routine disconnects as well `team_migration` events and similar. I'll also be making sure to expedite fixes for any issues with reconnection logic in particular, as I know that's been a pain for folks in the past.

So, I'd suggest that the best way to resolve this issue is to upgrade to the latest version. If you have any problems in doing that, please create a new issue and I'll try and help you in there.
