### ISSUE TITLE
team_rename and team_domain_change events

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-client#93]
Hey, Guys! I am trying to listen to the team_rename and team_domain_change and, apparently, the library is not firing them.

I can see that the team inside the client is setting the new attributes to the team object, but I do not understand how my code can receive a message (so I cna also update it into my database) 

      when "team_rename"
        @team.name = message.name

      when "team_domain_change"
        @team.domain = message.domain

Can you guys help me?

**Comment by vanm** [comment]
@brunosiqueira You can listen for events that this library handles internally (and doesn't emit out) by attaching a general listener for "raw_message" - it emits every message (including noisy ping/pong cycle messages)

https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L345

You can also submit a PR to this library that does emit the event for consumers - see my example of doing this for team_migration_started: 
https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L501

Hope that helps.

**Comment by brunosiqueira** [comment]
Hey, @vanm 

Thanks for your feedback. I forked the code and created the two events. And also I am trying to call my rep directly in my app dependencies to test it before submitting to your repo. :

     "slack-client": "git+https://github.com/brunosiqueira/node-slack-client.git#release_1.4.2"

The thing is that is not downloading the coffee script files. I saw that you have a grunt prepublish task, which generates the js files. But I have to confess that I got a little confuse on how requiring it properly. 

Thanks for your help (sorry if this is kinda an stupid question :-) )

**Comment by vanm** [comment]
@brunosiqueira no problem.  The best path forward is:

- Use "raw_message" in the current published version of this library and check for "type" in your production code i (it will work just fine).
- Submit a pull request to this repo `slack/node-slack-client` to include new emitters for those events and ping @l12s for review & merge (she is the maintainer).

Otherwise, to use a git hash in production via npm you'll need to `grunt coffee` locally and commit the JS files (this is not ideal and is a short-term hack until your pull request is merged and published on npm, so I don't recommend it).

Since raw_message works I think the best path is to listen to that and switch on type until your PR is merged.
